version: '2'

services:
  ethereum_exporter:
    container_name: ethereum_exporter
    image: "iderr/ethereum_block-exporter:v0.0.1"
    command: "-url http://ethereum:8545"
    ports:
      - "9368:9368"
